- name: Install module and role requirements
  become: true
  ansible.builtin.apt:
    name:
      - lxc
      - python3-lxc
      - acl

- ansible.builtin.import_tasks: lxc_user.yaml
  become: true

# Note trailing '/' of source path to set mode of copied files correctly
- name: Copy in container hooks
  become: true
  ansible.builtin.copy:
    src: hooks/
    dest: /usr/share/lxc/hooks/
    mode: '0755'
